server:
  port: 8081

spring:
  application:
    name: xk-base-info
  datasource:
    url: jdbc:mysql://192.168.3.111:3306/xinkong_base_info?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


